-- Real incident backfill from 'Bus Incidence' tab (data/sheet_import/gid_699362141.csv).
-- PROPOSAL ONLY -- not auto-run. Generated by scripts/extract-real-incidents.py.
-- Run AFTER seed_silverleaf.sql (buses must exist).
--
-- 11 of 13 real incident rows resolved to a known bus; 2 skipped
-- (unresolved bus reference): [('16-Feb-2026', 'Rental white', 'unresolved bus'), ('20-Feb-2026', 'T 215 DAU', 'unresolved bus')]
--
-- incidents.trip_id is NOT NULL and no trips exist for these historical dates (trips are
-- normally created live) -- this file creates the backing historical `trips` rows first,
-- direction defaulted to 'am' (incident text has no time-of-day signal), status 'completed'.
--
-- `type`/`severity` are inferred from incident text via keyword heuristics, not stated
-- explicitly in the sheet -- review before trusting severity classification specifically.

-- Step 1: backing historical trips (one per bus+date, idempotent).
insert into public.trips (bus_id, trip_date, direction, status)
select b.id, v.trip_date::date, 'am', 'completed'
from (values
  ('DSD', '2026-01-26'),
  ('Hiace DKS', '2026-02-11'),
  ('T 910 APW -', '2026-02-13'),
  ('Rental Hiace', '2026-02-18'),
  ('Hiace DKS', '2026-02-25'),
  ('T 910 APW -', '2026-03-06'),
  ('T 910 APW -', '2026-04-17'),
  ('Hiace DKS', '2026-04-27'),
  ('Coaster  CHE', '2026-05-20'),
  ('Hiace EBM', '2026-05-12'),
  ('Coaster  CHE', '2026-05-22')
) as v(bus_label, trip_date)
join public.buses b on b.label = v.bus_label
on conflict (bus_id, trip_date, direction) do nothing;

-- Step 2: the 13 real incidents, each linked to its backing trip above.
insert into public.incidents (trip_id, type, severity, notes, created_at)
select t.id, 'accident', 'medium', 'A motorcycle collided with the school bus. Both vehicles were moving at normal speed, and the impact did not cause serious damage. All students are safe and unharmed. The motorcycle riders (bodaboda) sustained minor injuries. | Location: Tuvaila | Solution: Leaders (Baraka and Aloyce) visited the scene and contacted the village chairman. After reviewing the situation, the school bus was released, as the school driver was not at fault. | Next steps: 1. Informing Karume about what happened as the bus is owned bu Ka rume car hire
2. Training to the drivers and bus riders on how to handle such situation once it happens', '2026-01-26'::timestamptz from public.trips t join public.buses b on b.id = t.bus_id where b.label = 'DSD' and t.trip_date = '2026-01-26'::date and t.direction = 'am' limit 1
union all
select t.id, 'accident', 'medium', 'Bajaji collided with the school bus. Minor damage happened to the car and know one was Injured or harmed | Location: Njiro | Solution: Driver comunicated with his leader (Francis) repoted what happpened whereby Francis allowed him to continue with the Journey as the effect was very minor | Next steps: - Meeting wiuththe driver for the process training
- Replace the brocken Indicator cape with the new one', '2026-02-11'::timestamptz from public.trips t join public.buses b on b.id = t.bus_id where b.label = 'Hiace DKS' and t.trip_date = '2026-02-11'::date and t.direction = 'am' limit 1
union all
select t.id, 'breakdown', 'low', 'The car broke Diff arm and cause the journy to stop | Location: Kiwawa | Solution: - Find another bus foe the backs up (Takinng students back home)', '2026-02-13'::timestamptz from public.trips t join public.buses b on b.id = t.bus_id where b.label = 'T 910 APW -' and t.trip_date = '2026-02-13'::date and t.direction = 'am' limit 1
union all
select t.id, 'breakdown', 'low', 'The vehicle got stuck on mud | Location: Ngaramtoni | Solution: The driver reported to Francis who coordinated with bus owner who brought another vehicle to pull it from mud | Next steps: Adviced the driver to look for alternative road incase our normal route is impassible', '2026-02-18'::timestamptz from public.trips t join public.buses b on b.id = t.bus_id where b.label = 'Rental Hiace' and t.trip_date = '2026-02-18'::date and t.direction = 'am' limit 1
union all
select t.id, 'breakdown', 'low', 'The vehicle engine cut off and there was no power supply neither could the vehicle start | Location: Mianzini | Solution: we got  a back up from driver Fredy bringing pupils to school | Next steps: Took wiring fundi to inspect the vehicle and repaired the vehicle', '2026-02-25'::timestamptz from public.trips t join public.buses b on b.id = t.bus_id where b.label = 'Hiace DKS' and t.trip_date = '2026-02-25'::date and t.direction = 'am' limit 1
union all
select t.id, 'breakdown', 'low', 'Broken Hub Holding Tyre | Location: Kiwawa | Solution: -The driver reported the issue to theHead driver,and another vehicle was dispatched to back him up so that the childrenwould not be delayed, as he was on route        -After that, the Head Driver called the technician again to come and inspect the problem and resolve it. | Next steps: -Advise the drivers to reduce speed when passing through areas with potholes to prevent the hub from breaking.', '2026-03-06'::timestamptz from public.trips t join public.buses b on b.id = t.bus_id where b.label = 'T 910 APW -' and t.trip_date = '2026-03-06'::date and t.direction = 'am' limit 1
union all
select t.id, 'breakdown', 'low', 'The radiator burst | Location: Kiwawa | Solution: -The driver reported the issue to theHead driver,and another vehicle was dispatched to back him up so that the childrenwould not be delayed, as he was on route        -After that, the Head Driver called the technician again to come and inspect the problem and resolve it. | Next steps: -Advise the drivers to reduce speed when passing through areas with potholes to prevent the radiator.', '2026-04-17'::timestamptz from public.trips t join public.buses b on b.id = t.bus_id where b.label = 'T 910 APW -' and t.trip_date = '2026-04-17'::date and t.direction = 'am' limit 1
union all
select t.id, 'breakdown', 'low', 'Broken torshen bar | Location: Kimandolu | Solution: Repaired | Next steps: Weekly vehicle inspection', '2026-04-27'::timestamptz from public.trips t join public.buses b on b.id = t.bus_id where b.label = 'Hiace DKS' and t.trip_date = '2026-04-27'::date and t.direction = 'am' limit 1
union all
select t.id, 'breakdown', 'low', 'Two flat tires | Location: Sakina | Solution: Ordered two new tires | Next steps: Weekly vehicle inspection', '2026-05-20'::timestamptz from public.trips t join public.buses b on b.id = t.bus_id where b.label = 'Coaster  CHE' and t.trip_date = '2026-05-20'::date and t.direction = 'am' limit 1
union all
select t.id, 'breakdown', 'low', 'Timing belt  and Head cylinder | Location: Shamsi | Solution: vehicle pulled to school and repair done | Next steps: Weekly vehicle inspection', '2026-05-12'::timestamptz from public.trips t join public.buses b on b.id = t.bus_id where b.label = 'Hiace EBM' and t.trip_date = '2026-05-12'::date and t.direction = 'am' limit 1
union all
select t.id, 'other', 'low', 'Tube housing, stab axle  and axle | Location: Tecnico | Solution: vehicle pulled to school  and repair in progress', '2026-05-22'::timestamptz from public.trips t join public.buses b on b.id = t.bus_id where b.label = 'Coaster  CHE' and t.trip_date = '2026-05-22'::date and t.direction = 'am' limit 1;

