-- Real maintenance/repair records from 'Repair & Maintenance' tab of the raw xlsx.
-- PROPOSAL ONLY -- not auto-run. Generated by scripts/extract-real-maintenance.py.
-- Run AFTER seed_silverleaf.sql (buses must exist).
--
-- 24 line items seeded, total 1,367,128 TZS.
--
-- NOT seeded (flagged, not guessed):
--   - 'Hiace DEP' block (24 line items, ~2.33M TZS, rows 975-995 -- duplicated at
--     1072-1094): Hiace DEP is NOT among the current 20 seeded buses. Real repair
--     history exists for a bus that doesn't exist in this app -- either a retired bus
--     whose plate should be reconciled, or a fleet gap. Flag to Kai before deciding.
--   - 'Labour charges' 350,000 TZS (row 1129) -- fleet-wide, not attributable to one bus.
--   - Two line items above (ROSA EBP&DYW, DEP&DKS) are SHARED multi-bus invoices --
--     attributed to one bus only per record, cost NOT split. Search this file for
--     'SHARED VISIT' / 'AMBIGUOUS' before trusting per-bus maintenance totals.

insert into public.maintenance_records (bus_id, title, category, cost, currency, service_date, notes)
values
  ((select id from public.buses where label = 'Coaster  CHE' limit 1), 'Hub seal (qty 2.0)', 'repair', 30000.00, 'TZS', '2026-05-28'::date, 'From ''Repair & Maintenance'' sheet, per-bus line-item block'),
  ((select id from public.buses where label = 'Coaster  CHE' limit 1), 'Axle seal (qty 2.0)', 'repair', 40000.00, 'TZS', '2026-05-28'::date, 'From ''Repair & Maintenance'' sheet, per-bus line-item block'),
  ((select id from public.buses where label = 'Coaster  CHE' limit 1), 'Hub bearing small (qty 1.0)', 'repair', 63333.00, 'TZS', '2026-05-28'::date, 'From ''Repair & Maintenance'' sheet, per-bus line-item block'),
  ((select id from public.buses where label = 'Coaster  CHE' limit 1), 'Hub bearing big (qty 1.0)', 'repair', 70000.00, 'TZS', '2026-05-28'::date, 'From ''Repair & Maintenance'' sheet, per-bus line-item block'),
  ((select id from public.buses where label = 'Coaster  CHE' limit 1), 'Greace (qty 1.0)', 'repair', 25000.00, 'TZS', '2026-05-28'::date, 'From ''Repair & Maintenance'' sheet, per-bus line-item block'),
  ((select id from public.buses where label = 'Coaster  CHE' limit 1), 'Brake fluid 1/2 (qty 1.0)', 'repair', 7000.00, 'TZS', '2026-05-28'::date, 'From ''Repair & Maintenance'' sheet, per-bus line-item block'),
  ((select id from public.buses where label = 'Coaster  CHE' limit 1), 'Silicone (qty 1.0)', 'repair', 15000.00, 'TZS', '2026-05-28'::date, 'From ''Repair & Maintenance'' sheet, per-bus line-item block'),
  ((select id from public.buses where label = 'Coaster  CHE' limit 1), 'Diff Oil no 140 T5 (qty 1.0)', 'repair', 80000.00, 'TZS', '2026-05-28'::date, 'From ''Repair & Maintenance'' sheet, per-bus line-item block'),
  ((select id from public.buses where label = 'Coaster  CHE' limit 1), 'Bolt (qty 2.0)', 'repair', 6000.00, 'TZS', '2026-05-28'::date, 'From ''Repair & Maintenance'' sheet, per-bus line-item block'),
  ((select id from public.buses where label = 'Coaster  CHE' limit 1), 'U-Bolt (qty 2.0)', 'repair', 40000.00, 'TZS', '2026-05-28'::date, 'From ''Repair & Maintenance'' sheet, per-bus line-item block'),
  ((select id from public.buses where label = 'T 910 APW -' limit 1), 'Engine oil (12L)', 'repair', 110000.00, 'TZS', null, 'From ''Repair & Maintenance'' sheet, BUSES MAINTENANCE invoice block (undated)'),
  ((select id from public.buses where label = 'T 910 APW -' limit 1), 'Oil fiLtrer', 'repair', 10000.00, 'TZS', null, 'From ''Repair & Maintenance'' sheet, BUSES MAINTENANCE invoice block (undated)'),
  ((select id from public.buses where label = 'T 910 APW -' limit 1), 'Diesel FiLtrer', 'repair', 10000.00, 'TZS', null, 'From ''Repair & Maintenance'' sheet, BUSES MAINTENANCE invoice block (undated)'),
  ((select id from public.buses where label = 'T 910 APW -' limit 1), 'Battery VAT included', 'repair', 166250.00, 'TZS', null, 'From ''Repair & Maintenance'' sheet, BUSES MAINTENANCE invoice block (undated)'),
  ((select id from public.buses where label = 'T 108 DYW' limit 1), 'Engine oil (20L)', 'repair', 180000.00, 'TZS', null, 'SHARED VISIT: sheet groups this under ''ROSA EBP & DYW'' (both T326 EBP and T108 DYW serviced together); attributed here to T108 DYW only since the ''Shock up for DYW'' line explicitly names it -- cost is NOT split, review before trusting this attribution for T326 EBP''s own history.'),
  ((select id from public.buses where label = 'T 108 DYW' limit 1), 'Oil fiLtrer', 'repair', 10000.00, 'TZS', null, 'SHARED VISIT: sheet groups this under ''ROSA EBP & DYW'' (both T326 EBP and T108 DYW serviced together); attributed here to T108 DYW only since the ''Shock up for DYW'' line explicitly names it -- cost is NOT split, review before trusting this attribution for T326 EBP''s own history.'),
  ((select id from public.buses where label = 'T 108 DYW' limit 1), 'Diesel fiLtrer', 'repair', 10000.00, 'TZS', null, 'SHARED VISIT: sheet groups this under ''ROSA EBP & DYW'' (both T326 EBP and T108 DYW serviced together); attributed here to T108 DYW only since the ''Shock up for DYW'' line explicitly names it -- cost is NOT split, review before trusting this attribution for T326 EBP''s own history.'),
  ((select id from public.buses where label = 'T 108 DYW' limit 1), 'Shock up for DYW', 'repair', 80000.00, 'TZS', null, 'SHARED VISIT: sheet groups this under ''ROSA EBP & DYW'' (both T326 EBP and T108 DYW serviced together); attributed here to T108 DYW only since the ''Shock up for DYW'' line explicitly names it -- cost is NOT split, review before trusting this attribution for T326 EBP''s own history.'),
  ((select id from public.buses where label = 'Hiace DKS' limit 1), 'Engine oil (14L)', 'repair', 130000.00, 'TZS', null, 'AMBIGUOUS: sheet header says ''DEP & DKS'' but one item text says ''Shock up front EBM'' -- likely a 3-way shared visit (DEP not in current fleet, so attributed to Hiace DKS only). Cost NOT split. Review before trusting.'),
  ((select id from public.buses where label = 'Hiace DKS' limit 1), 'Diesel fiLtrer', 'repair', 10000.00, 'TZS', null, 'AMBIGUOUS: sheet header says ''DEP & DKS'' but one item text says ''Shock up front EBM'' -- likely a 3-way shared visit (DEP not in current fleet, so attributed to Hiace DKS only). Cost NOT split. Review before trusting.'),
  ((select id from public.buses where label = 'Hiace DKS' limit 1), 'Oil fiLtrer', 'repair', 10000.00, 'TZS', null, 'AMBIGUOUS: sheet header says ''DEP & DKS'' but one item text says ''Shock up front EBM'' -- likely a 3-way shared visit (DEP not in current fleet, so attributed to Hiace DKS only). Cost NOT split. Review before trusting.'),
  ((select id from public.buses where label = 'Hiace DKS' limit 1), 'Shock up front EBM', 'repair', 60000.00, 'TZS', null, 'AMBIGUOUS: sheet header says ''DEP & DKS'' but one item text says ''Shock up front EBM'' -- likely a 3-way shared visit (DEP not in current fleet, so attributed to Hiace DKS only). Cost NOT split. Review before trusting.'),
  ((select id from public.buses where label = 'Hiace DKS' limit 1), 'Buffer rubber', 'repair', 15000.00, 'TZS', null, 'AMBIGUOUS: sheet header says ''DEP & DKS'' but one item text says ''Shock up front EBM'' -- likely a 3-way shared visit (DEP not in current fleet, so attributed to Hiace DKS only). Cost NOT split. Review before trusting.'),
  ((select id from public.buses where label = 'Hiace DKS' limit 1), 'Tyres ??', 'repair', 189544.96, 'TZS', null, 'AMBIGUOUS: sheet header says ''DEP & DKS'' but one item text says ''Shock up front EBM'' -- likely a 3-way shared visit (DEP not in current fleet, so attributed to Hiace DKS only). Cost NOT split. Review before trusting.');

