-- Real fleet-wide R&M budget + actuals from 'Actual vs Budget' tab (2026 Transport
-- Master sheet.xlsx, A1:M4) -- flat 1,000,000 TZS/month budget, real actuals only
-- exist for Jan-Mar 2026 in the sheet (Apr-Dec blank there).
-- PROPOSAL ONLY -- not auto-run. Generated by scripts/extract-real-maintenance-budget.py.
-- Additive to (not replacing) the existing seed_finance.sql demo rows.
--
-- school_id is left NULL: this budget is fleet-wide per the sheet, not scoped to one
-- campus like the existing 'Usariver Fuel Q3'/'Usariver Ops Q3' demo rows.
--
-- Jan actual (9,283,085) is 9x the monthly budget -- a real, large budget overrun,
-- worth surfacing on the dashboard once loaded, not a data error.
--
-- NOTE: these actuals are fleet-wide monthly totals and are MUCH larger than (and do
-- not reconcile with) the itemized per-bus records in seed_real_maintenance.sql --
-- that sheet is only a partial line-item sample, not a full accounting.

insert into public.budgets (school_id, name, category, period_start, period_end, amount, currency, notes)
values
  (null, 'Fleet R&M January 2026', 'maintenance', '2026-01-01'::date, '2026-01-31'::date, 1000000.00, 'TZS', 'From ''Actual vs Budget'' sheet -- flat 1,000,000/month fleet-wide R&M budget'),
  (null, 'Fleet R&M February 2026', 'maintenance', '2026-02-01'::date, '2026-02-28'::date, 1000000.00, 'TZS', 'From ''Actual vs Budget'' sheet -- flat 1,000,000/month fleet-wide R&M budget'),
  (null, 'Fleet R&M March 2026', 'maintenance', '2026-03-01'::date, '2026-03-31'::date, 1000000.00, 'TZS', 'From ''Actual vs Budget'' sheet -- flat 1,000,000/month fleet-wide R&M budget'),
  (null, 'Fleet R&M April 2026', 'maintenance', '2026-04-01'::date, '2026-04-30'::date, 1000000.00, 'TZS', 'From ''Actual vs Budget'' sheet -- flat 1,000,000/month fleet-wide R&M budget'),
  (null, 'Fleet R&M May 2026', 'maintenance', '2026-05-01'::date, '2026-05-31'::date, 1000000.00, 'TZS', 'From ''Actual vs Budget'' sheet -- flat 1,000,000/month fleet-wide R&M budget'),
  (null, 'Fleet R&M June 2026', 'maintenance', '2026-06-01'::date, '2026-06-30'::date, 1000000.00, 'TZS', 'From ''Actual vs Budget'' sheet -- flat 1,000,000/month fleet-wide R&M budget'),
  (null, 'Fleet R&M July 2026', 'maintenance', '2026-07-01'::date, '2026-07-31'::date, 1000000.00, 'TZS', 'From ''Actual vs Budget'' sheet -- flat 1,000,000/month fleet-wide R&M budget'),
  (null, 'Fleet R&M August 2026', 'maintenance', '2026-08-01'::date, '2026-08-31'::date, 1000000.00, 'TZS', 'From ''Actual vs Budget'' sheet -- flat 1,000,000/month fleet-wide R&M budget'),
  (null, 'Fleet R&M September 2026', 'maintenance', '2026-09-01'::date, '2026-09-30'::date, 1000000.00, 'TZS', 'From ''Actual vs Budget'' sheet -- flat 1,000,000/month fleet-wide R&M budget'),
  (null, 'Fleet R&M October 2026', 'maintenance', '2026-10-01'::date, '2026-10-31'::date, 1000000.00, 'TZS', 'From ''Actual vs Budget'' sheet -- flat 1,000,000/month fleet-wide R&M budget'),
  (null, 'Fleet R&M November 2026', 'maintenance', '2026-11-01'::date, '2026-11-30'::date, 1000000.00, 'TZS', 'From ''Actual vs Budget'' sheet -- flat 1,000,000/month fleet-wide R&M budget'),
  (null, 'Fleet R&M December 2026', 'maintenance', '2026-12-01'::date, '2026-12-31'::date, 1000000.00, 'TZS', 'From ''Actual vs Budget'' sheet -- flat 1,000,000/month fleet-wide R&M budget');

insert into public.expenses (school_id, bus_id, category, title, amount, currency, spent_on, notes)
values
  (null, null, 'maintenance', 'Fleet R&M actual spend -- January 2026', 9283085.00, 'TZS', '2026-01-31'::date, 'From ''Actual vs Budget'' sheet -- real fleet-wide monthly total, not itemized per-bus (see seed_real_maintenance.sql for the partial itemized sample)'),
  (null, null, 'maintenance', 'Fleet R&M actual spend -- February 2026', 1748150.00, 'TZS', '2026-02-28'::date, 'From ''Actual vs Budget'' sheet -- real fleet-wide monthly total, not itemized per-bus (see seed_real_maintenance.sql for the partial itemized sample)'),
  (null, null, 'maintenance', 'Fleet R&M actual spend -- March 2026', 2464200.00, 'TZS', '2026-03-31'::date, 'From ''Actual vs Budget'' sheet -- real fleet-wide monthly total, not itemized per-bus (see seed_real_maintenance.sql for the partial itemized sample)');

