#!/usr/bin/env python3
"""Extract the 13 real incident reports from data/sheet_import/gid_699362141.csv
("Bus Incidence" tab) and generate a seed proposal for `incidents`.

`incidents.trip_id` is NOT NULL, and no trips exist for these historical
dates (trips are only created live) -- so this script ALSO generates the
backing historical `trips` rows needed, one per (bus, date), direction
defaulted to 'am' (incident text has no time-of-day signal).

PROPOSAL ONLY. Writes supabase/seed_real_incidents.sql -- not auto-run.
"""

from __future__ import annotations

import csv
import re
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_SQL = ROOT / "supabase" / "seed_real_incidents.sql"

# bus code/name as seen in the incident log -> real bus label in the `buses` table
BUS_LABEL = {
    "DSD": "DSD",
    "T991 DSD": "DSD",
    "T 348 DKS": "Hiace DKS",
    "T910 APW": "T 910 APW -",
    "T 910 APW": "T 910 APW -",
    "T 400 BMC": "Rental Hiace",  # AM campus Rental Hiace, route Ngaramtoni -- confirmed real plate
    "CHE": "Coaster  CHE",
    "T 418 EBM": "Hiace EBM",
}

TYPE_KEYWORDS = [
    (r"collid|hit a|bajaji", "accident"),
    (r"broke|broken|cut off|stuck|stall|burst|flat tire|belt|torshen|hub", "breakdown"),
    (r"delay", "delay"),
    (r"injur|medical|hurt", "medical"),
]


def classify_type(text: str) -> str:
    low = text.lower()
    for pattern, t in TYPE_KEYWORDS:
        if re.search(pattern, low):
            return t
    return "other"


def classify_severity(text: str) -> str:
    low = text.lower()
    if "injur" in low or "hurt" in low:
        return "medium"
    if "minor" in low or "no damage" in low or "no one was" in low or "know one was" in low:
        return "low"
    return "low"


def parse_date(raw: str) -> str | None:
    for fmt in ("%d-%b-%Y",):
        try:
            return datetime.strptime(raw.strip(), fmt).date().isoformat()
        except ValueError:
            continue
    return None


def sql_str(v) -> str:
    if v is None:
        return "null"
    return "'" + str(v).replace("'", "''") + "'"


def main() -> None:
    with (ROOT / "data" / "sheet_import" / "gid_699362141.csv").open(encoding="utf-8") as f:
        rows = list(csv.reader(f))

    records = []
    skipped = []
    for row in rows[1:14]:
        if not row or not row[0].strip():
            continue
        date_raw, campus, bus_no, driver, incidence, location, solution, next_steps = row[:8]
        date_iso = parse_date(date_raw)
        bus_label = BUS_LABEL.get(bus_no.strip())
        if not date_iso or not bus_label:
            skipped.append((date_raw, bus_no, "unresolved bus" if date_iso else "bad date"))
            continue
        notes_parts = [incidence.strip()]
        if location.strip():
            notes_parts.append(f"Location: {location.strip()}")
        if solution.strip():
            notes_parts.append(f"Solution: {solution.strip()}")
        if next_steps.strip():
            notes_parts.append(f"Next steps: {next_steps.strip()}")
        records.append(
            {
                "date": date_iso,
                "bus_label": bus_label,
                "type": classify_type(incidence),
                "severity": classify_severity(incidence),
                "notes": " | ".join(notes_parts)[:2000],
            }
        )

    print(f"Extracted {len(records)} incidents; skipped {len(skipped)}: {skipped}")

    lines = [
        "-- Real incident backfill from 'Bus Incidence' tab (data/sheet_import/gid_699362141.csv).",
        "-- PROPOSAL ONLY -- not auto-run. Generated by scripts/extract-real-incidents.py.",
        "-- Run AFTER seed_silverleaf.sql (buses must exist).",
        "--",
        f"-- {len(records)} of 13 real incident rows resolved to a known bus; {len(skipped)} skipped",
        f"-- (unresolved bus reference): {skipped}",
        "--",
        "-- incidents.trip_id is NOT NULL and no trips exist for these historical dates (trips are",
        "-- normally created live) -- this file creates the backing historical `trips` rows first,",
        "-- direction defaulted to 'am' (incident text has no time-of-day signal), status 'completed'.",
        "--",
        "-- `type`/`severity` are inferred from incident text via keyword heuristics, not stated",
        "-- explicitly in the sheet -- review before trusting severity classification specifically.",
        "",
        "-- Step 1: backing historical trips (one per bus+date, idempotent).",
        "insert into public.trips (bus_id, trip_date, direction, status)",
        "select b.id, v.trip_date::date, 'am', 'completed'",
        "from (values",
    ]

    trip_value_rows = []
    seen_trip_keys = set()
    for r in records:
        key = (r["bus_label"], r["date"])
        if key in seen_trip_keys:
            continue
        seen_trip_keys.add(key)
        trip_value_rows.append(f"  ({sql_str(r['bus_label'])}, {sql_str(r['date'])})")
    lines.append(",\n".join(trip_value_rows))
    lines.append(") as v(bus_label, trip_date)")
    lines.append("join public.buses b on b.label = v.bus_label")
    lines.append("on conflict (bus_id, trip_date, direction) do nothing;")
    lines.append("")

    lines.append("-- Step 2: the 13 real incidents, each linked to its backing trip above.")
    lines.append("insert into public.incidents (trip_id, type, severity, notes, created_at)")
    incident_rows = []
    for r in records:
        incident_rows.append(
            "select t.id, "
            + sql_str(r["type"])
            + ", "
            + sql_str(r["severity"])
            + ", "
            + sql_str(r["notes"])
            + ", "
            + sql_str(r["date"])
            + "::timestamptz "
            + "from public.trips t join public.buses b on b.id = t.bus_id "
            + f"where b.label = {sql_str(r['bus_label'])} and t.trip_date = {sql_str(r['date'])}::date "
            + "and t.direction = 'am' limit 1"
        )
    lines.append("\nunion all\n".join(incident_rows) + ";")
    lines.append("")

    OUT_SQL.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_SQL}")


if __name__ == "__main__":
    main()
