#!/usr/bin/env python3
"""Extract the real fleet-wide R&M budget + actual monthly spend from the
'Actual vs Budget' tab (A1:M4, confirmed by direct read -- flat 1,000,000/
month budget, only Jan/Feb/Mar 2026 have real actuals filled in).

PROPOSAL ONLY. Writes supabase/seed_real_maintenance_budget.sql. This budget
is fleet-wide (not campus-scoped) per the sheet -- school_id left NULL,
unlike the existing seed_finance.sql demo rows which are Usariver-only.

Also seeds the 3 real monthly actuals as `expenses` rows (category=
maintenance, bus_id NULL = fleet-wide) so the P&L budget-vs-actual dashboard
has something real to compare against for Jan-Mar 2026 -- these monthly
totals are much larger than (and don't reconcile with) the itemized repair
line items in seed_real_maintenance.sql, since that sheet is only a partial
sample, not a full accounting of all fleet repair spend.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_SQL = ROOT / "supabase" / "seed_real_maintenance_budget.sql"

MONTHLY_BUDGET = 1_000_000.0
MONTHS = [
    ("January", "01", 31), ("February", "02", 28), ("March", "03", 31),
    ("April", "04", 30), ("May", "05", 31), ("June", "06", 30),
    ("July", "07", 31), ("August", "08", 31), ("September", "09", 30),
    ("October", "10", 31), ("November", "11", 30), ("December", "12", 31),
]
ACTUALS = {"January": 9_283_085.0, "February": 1_748_150.0, "March": 2_464_200.0}


def sql_str(v) -> str:
    return "'" + str(v).replace("'", "''") + "'"


def main() -> None:
    lines = [
        "-- Real fleet-wide R&M budget + actuals from 'Actual vs Budget' tab (2026 Transport",
        "-- Master sheet.xlsx, A1:M4) -- flat 1,000,000 TZS/month budget, real actuals only",
        "-- exist for Jan-Mar 2026 in the sheet (Apr-Dec blank there).",
        "-- PROPOSAL ONLY -- not auto-run. Generated by scripts/extract-real-maintenance-budget.py.",
        "-- Additive to (not replacing) the existing seed_finance.sql demo rows.",
        "--",
        "-- school_id is left NULL: this budget is fleet-wide per the sheet, not scoped to one",
        "-- campus like the existing 'Usariver Fuel Q3'/'Usariver Ops Q3' demo rows.",
        "--",
        "-- Jan actual (9,283,085) is 9x the monthly budget -- a real, large budget overrun,",
        "-- worth surfacing on the dashboard once loaded, not a data error.",
        "--",
        "-- NOTE: these actuals are fleet-wide monthly totals and are MUCH larger than (and do",
        "-- not reconcile with) the itemized per-bus records in seed_real_maintenance.sql --",
        "-- that sheet is only a partial line-item sample, not a full accounting.",
        "",
        "insert into public.budgets (school_id, name, category, period_start, period_end, amount, currency, notes)",
        "values",
    ]

    budget_rows = []
    for name, num, days in MONTHS:
        budget_rows.append(
            "  (null, "
            + sql_str(f"Fleet R&M {name} 2026")
            + ", 'maintenance', "
            + sql_str(f"2026-{num}-01") + "::date, "
            + sql_str(f"2026-{num}-{days:02d}") + "::date, "
            + f"{MONTHLY_BUDGET:.2f}, 'TZS', "
            + sql_str("From 'Actual vs Budget' sheet -- flat 1,000,000/month fleet-wide R&M budget")
            + ")"
        )
    lines.append(",\n".join(budget_rows) + ";")
    lines.append("")

    lines.append("insert into public.expenses (school_id, bus_id, category, title, amount, currency, spent_on, notes)")
    lines.append("values")
    expense_rows = []
    for name, num, days in MONTHS:
        if name not in ACTUALS:
            continue
        amount = ACTUALS[name]
        expense_rows.append(
            "  (null, null, 'maintenance', "
            + sql_str(f"Fleet R&M actual spend -- {name} 2026")
            + f", {amount:.2f}, 'TZS', "
            + sql_str(f"2026-{num}-{days:02d}") + "::date, "
            + sql_str(
                "From 'Actual vs Budget' sheet -- real fleet-wide monthly total, not itemized "
                "per-bus (see seed_real_maintenance.sql for the partial itemized sample)"
            )
            + ")"
        )
    lines.append(",\n".join(expense_rows) + ";")
    lines.append("")

    OUT_SQL.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_SQL}: 12 budget rows + {len(expense_rows)} actual-expense rows")


if __name__ == "__main__":
    main()
