#!/usr/bin/env python3
"""Rename Irene's already-live per-student "Pickup point" stops to their real
destination names (e.g. "Kiwawa", "Mangusha") from the Transport Users sheet.

Does NOT touch coordinates or assignments -- update is scoped to `stops.name
= 'Pickup point'` only, and only for students whose name maps to exactly one
destination in data/import/student_stops.json (ambiguous duplicate names are
skipped, not guessed).

PROPOSAL ONLY. Writes supabase/rename_pickup_point_stops.sql -- not auto-run.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_SQL = ROOT / "supabase" / "rename_pickup_point_stops.sql"


def sql_str(v: str) -> str:
    return "'" + v.replace("'", "''") + "'"


def main() -> None:
    with (ROOT / "data" / "import" / "student_stops.json").open(encoding="utf-8") as f:
        records = json.load(f)

    by_name: dict[tuple[str, str], set[str]] = defaultdict(set)
    dest_for_name: dict[tuple[str, str], str] = {}
    for r in records:
        key = (r["first_name"].strip().lower(), r["last_name"].strip().lower())
        by_name[key].add(r["destination"].strip())
        dest_for_name[key] = r["destination"].strip()

    unambiguous = {k: v for k, v in dest_for_name.items() if len(by_name[k]) == 1}
    ambiguous = {k: by_name[k] for k in by_name if len(by_name[k]) > 1}

    print(f"Total students with a known destination: {len(dest_for_name)}")
    print(f"Unambiguous (single destination for that name): {len(unambiguous)}")
    print(f"Ambiguous (name maps to >1 different destination, skipped): {len(ambiguous)}")
    for k, dests in list(ambiguous.items())[:10]:
        print(f"  skipped: {k[0].title()} {k[1].title()} -> {dests}")

    lines = [
        "-- Rename Irene's already-live per-student 'Pickup point' stops to their real",
        "-- destination names (e.g. 'Kiwawa', 'Mangusha') from the Transport Users sheet.",
        "-- PROPOSAL ONLY -- not auto-run. Generated by scripts/rename-pickup-point-stops.py.",
        "--",
        "-- Does NOT touch coordinates, route_stops, or student_stop_assignments -- this",
        "-- only updates stops.name, and ONLY where the current name is still the generic",
        "-- 'Pickup point' placeholder (never overwrites a stop someone already renamed).",
        "--",
        f"-- {len(unambiguous)} students have exactly one known destination name and will be",
        f"-- renamed; {len(ambiguous)} were skipped because the same name maps to more than",
        "-- one different destination in the sheet (likely two different real people sharing",
        "-- a name) -- review those manually rather than guess which destination is right.",
        "--",
        "-- Separately, unrelated to this rename: 2 of the 405 live stops have garbage",
        "-- coordinates (lat -8696869, lng 89589, ids 017c7e1c-563d-4862-9826-3b4a6666d9ef",
        "-- and f3a552b0-170a-4333-9a76-3c35b616aea6) from an unvalidated parse in Irene's",
        "-- import script -- not fixed here since the correct coordinate isn't known; flag",
        "-- to Irene to re-check those specific source rows.",
        "",
        "update public.stops s",
        "set name = v.destination",
        "from (values",
    ]

    rows = []
    for (first, last), dest in sorted(unambiguous.items()):
        rows.append(f"  ({sql_str(first)}, {sql_str(last)}, {sql_str(dest[:120])})")
    lines.append(",\n".join(rows))
    lines.append(") as v(first_name, last_name, destination)")
    lines.append("join public.students st on lower(st.first_name) = v.first_name and lower(st.last_name) = v.last_name")
    lines.append("join public.student_stop_assignments ssa on ssa.student_id = st.id")
    lines.append("where s.id = ssa.stop_id and s.name = 'Pickup point';")
    lines.append("")

    OUT_SQL.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nWrote {OUT_SQL}")


if __name__ == "__main__":
    main()
